#!/bin/bash
set -e
source /etc/bashrc
echo `hostname`
whoami
HERE=$PWD

# compile exefile for actual run
COMPILER="nvcc "
EXE="/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/exefiles/Cosmica"
SOURCE=" /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/kernel_test.cu "
SOURCE+=` ls /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/sources/*.cu`
HEADER="/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/headers/"

ptxas=" --ptxas-options="-v" "
resource=" --resource-usage "
el=" -rdc=true"
openmp=" -Xcompiler -fopenmp"
opt=" --use_fast_math "

$COMPILER $ptxas $resource $el $VAR $openmp $opt  -I $HEADER -o $EXE $SOURCE

##########################

cd /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/outfile 
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryllium_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryllium_0.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryllium_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryllium_1.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryllium_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryllium_2.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryllium_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryllium_3.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryllium_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryllium_4.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryllium_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryllium_5.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryllium_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryllium_6.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryllium_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryllium_7.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryllium_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryllium_8.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryllium_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryllium_9.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryl7_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryllium_0.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryl7_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryllium_1.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryl7_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryllium_2.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryl7_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryllium_3.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryl7_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryllium_4.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryl7_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryllium_5.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryl7_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryllium_6.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryl7_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryllium_7.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryl7_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryllium_8.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryl7_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryllium_9.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryl10_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryllium_0.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryl10_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryllium_1.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryl10_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryllium_2.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryl10_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryllium_3.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryl10_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryllium_4.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryl10_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryllium_5.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryl10_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryllium_6.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryl10_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryllium_7.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryl10_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryllium_8.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryl10_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryllium_9.out 2>&1
# CUDA_VISIBLE_DEVICES=4 only A30 board
# CUDA_VISIBLE_DEVICES=0,1,2,3 only x A40 board
echo Done....