#!/bin/bash
set -e
source /etc/bashrc
echo `hostname`
whoami
HERE=$PWD

# compile exefile for actual run
COMPILER="nvcc "
EXE="/home/nfsdisk/DevGC/Cosmica_1D/Trivial_1D-rigi/exefiles/Trivial"
SOURCE=" /home/nfsdisk/DevGC/Cosmica_1D/Trivial_1D-rigi/Trivial_1D.cu "
ptxas=" --ptxas-options="-v" "
resource=" --resource-usage "
el=" -rdc=true"
openmp=" -Xcompiler -fopenmp"
opt=" --use_fast_math "

$COMPILER $ptxas $resource $el $VAR $openmp $opt -o $EXE $SOURCE

##########################

unset CUDA_VISIBLE_DEVICES
cd /home/nfsdisk/DevGC/Cosmica_1D/Trivial_1D-rigi/runned_tests/AMS-02_PRL2014/outfile 
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/Cosmica_1D/Trivial_1D-rigi/runned_tests/AMS-02_PRL2014/Input_Positron_TKO_20110509_20131121_r00100_lat00000.txt >/home/nfsdisk/DevGC/Cosmica_1D/Trivial_1D-rigi/runned_tests/AMS-02_PRL2014/run/run_AMS-02_PRL2014_Positron_Positron_0.out 2>&1
# CUDA_VISIBLE_DEVICES=0,1,2,3 only A40 board
# CUDA_VISIBLE_DEVICES=4,5,6,7 only A30 board
echo Done....