#!/bin/bash
set -e
#source /etc/bashrc
echo `hostname`
whoami
HERE=$PWD

# compile exefile for actual run
COMPILER="nvcc "
EXE="./Cosmica_1D-en/exefiles/Cosmica"
SOURCE=" ./Cosmica_1D-en/kernel_test.cu "
SOURCE+=` ls Cosmica_1D-en/sources/*.cu`
HEADER="./Cosmica_1D-en/headers/"

ptxas=" --ptxas-options="-v" "
resource=" --resource-usage "
el=" -rdc=true"
openmp=" -Xcompiler -fopenmp"
opt=" --use_fast_math "

$COMPILER $ptxas $resource $el $VAR $openmp $opt  -I $HEADER -o $EXE $SOURCE

##########################

unset CUDA_VISIBLE_DEVICES
cd /home/nfsdisk/DevGC/Cosmica_1D/Cosmica_1D-en/runned_tests/AMS-02_PRL2015/outfile
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 $EXE -vv -i /home/nfsdisk/DevGC/Cosmica_1D/Cosmica_1D-en/runned_tests/AMS-02_PRL2015/Input_Proton_TKO_20110509_20131121_r00100_lat00000.txt >/home/nfsdisk/DevGC/Cosmica_1D/Cosmica_1D-en/runned_tests/AMS-02_PRL2015/run/run_AMS-02_PRL2015_Proton_Proton_0.out 2>&1
# CUDA_VISIBLE_DEVICES=0,1,2,3 only A40 board
# CUDA_VISIBLE_DEVICES=4,5,6,7 only A30 board
echo Done....