#!/bin/bash
set -e
source /etc/bashrc
echo `hostname`
whoami
HERE=$PWD

# compile exefile for actual run
COMPILER="nvcc "
EXE="/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/exefiles/Cosmica"
SOURCE=" /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/kernel_test.cu "
SOURCE+=` ls /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/sources/*.cu`
HEADER="/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/headers/"

ptxas=" --ptxas-options="-v" "
resource=" --resource-usage "
el=" -rdc=true"
openmp=" -Xcompiler -fopenmp"
opt=" --use_fast_math "

$COMPILER $ptxas $resource $el $VAR $openmp $opt  -I $HEADER -o $EXE $SOURCE

##########################

unset CUDA_VISIBLE_DEVICES
cd /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/outfile 
CUDA_VISIBLE_DEVICES=4,5,6,7 $EXE -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryllium_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryllium_0.out 2>&1
CUDA_VISIBLE_DEVICES=4,5,6,7 $EXE -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryllium_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryllium_1.out 2>&1
CUDA_VISIBLE_DEVICES=4,5,6,7 $EXE -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryllium_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryllium_2.out 2>&1
CUDA_VISIBLE_DEVICES=4,5,6,7 $EXE -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryllium_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryllium_3.out 2>&1
CUDA_VISIBLE_DEVICES=4,5,6,7 $EXE -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryllium_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryllium_4.out 2>&1
CUDA_VISIBLE_DEVICES=4,5,6,7 $EXE -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryllium_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryllium_5.out 2>&1
CUDA_VISIBLE_DEVICES=4,5,6,7 $EXE -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryllium_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryllium_6.out 2>&1
CUDA_VISIBLE_DEVICES=4,5,6,7 $EXE -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryllium_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryllium_7.out 2>&1
CUDA_VISIBLE_DEVICES=4,5,6,7 $EXE -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryllium_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryllium_8.out 2>&1
CUDA_VISIBLE_DEVICES=4,5,6,7 $EXE -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryllium_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryllium_9.out 2>&1
CUDA_VISIBLE_DEVICES=4,5,6,7 $EXE -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryl7_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryl7_0.out 2>&1
CUDA_VISIBLE_DEVICES=4,5,6,7 $EXE -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryl7_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryl7_1.out 2>&1
CUDA_VISIBLE_DEVICES=4,5,6,7 $EXE -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryl7_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryl7_2.out 2>&1
CUDA_VISIBLE_DEVICES=4,5,6,7 $EXE -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryl7_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryl7_3.out 2>&1
CUDA_VISIBLE_DEVICES=4,5,6,7 $EXE -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryl7_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryl7_4.out 2>&1
CUDA_VISIBLE_DEVICES=4,5,6,7 $EXE -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryl7_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryl7_5.out 2>&1
CUDA_VISIBLE_DEVICES=4,5,6,7 $EXE -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryl7_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryl7_6.out 2>&1
CUDA_VISIBLE_DEVICES=4,5,6,7 $EXE -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryl7_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryl7_7.out 2>&1
CUDA_VISIBLE_DEVICES=4,5,6,7 $EXE -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryl7_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryl7_8.out 2>&1
CUDA_VISIBLE_DEVICES=4,5,6,7 $EXE -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryl7_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryl7_9.out 2>&1
CUDA_VISIBLE_DEVICES=4,5,6,7 $EXE -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryl10_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryl10_0.out 2>&1
CUDA_VISIBLE_DEVICES=4,5,6,7 $EXE -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryl10_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryl10_1.out 2>&1
CUDA_VISIBLE_DEVICES=4,5,6,7 $EXE -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryl10_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryl10_2.out 2>&1
CUDA_VISIBLE_DEVICES=4,5,6,7 $EXE -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryl10_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryl10_3.out 2>&1
CUDA_VISIBLE_DEVICES=4,5,6,7 $EXE -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryl10_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryl10_4.out 2>&1
CUDA_VISIBLE_DEVICES=4,5,6,7 $EXE -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryl10_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryl10_5.out 2>&1
CUDA_VISIBLE_DEVICES=4,5,6,7 $EXE -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryl10_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryl10_6.out 2>&1
CUDA_VISIBLE_DEVICES=4,5,6,7 $EXE -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryl10_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryl10_7.out 2>&1
CUDA_VISIBLE_DEVICES=4,5,6,7 $EXE -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryl10_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryl10_8.out 2>&1
CUDA_VISIBLE_DEVICES=4,5,6,7 $EXE -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/Input_Beryl10_20110509_20160509_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V3-speedtest/runned_tests/AMS-02_PRL2018/run/run_AMS-02_PRL2018_Beryl10_9.out 2>&1
# CUDA_VISIBLE_DEVICES=0,1,2,3 only A40 board
# CUDA_VISIBLE_DEVICES=4,5,6,7 only A30 board
echo Done....