#!/bin/bash
set -e
source /etc/bashrc
echo `hostname`
whoami
HERE=$PWD

# compile exefile for actual run
COMPILER="nvcc "
EXE="/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/exefiles/Cosmica"
SOURCE=" /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/kernel_test.cu "
SOURCE+=` ls /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/sources/*.cu`
HEADER="/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/headers/"

ptxas=" --ptxas-options="-v" "
resource=" --resource-usage "
el=" -rdc=true"
openmp=" -Xcompiler -fopenmp"
opt=" --use_fast_math "

$COMPILER $ptxas $resource $el $VAR $openmp $opt  -I $HEADER -o $EXE $SOURCE

##########################

cd /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2015/outfile 
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2015/Input_Proton_TKO_20110509_20131121_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2015/run/run_AMS-02_PRL2015_Proton_TKO_0.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2015/Input_Proton_TKO_20110509_20131121_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2015/run/run_AMS-02_PRL2015_Proton_TKO_1.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2015/Input_Proton_TKO_20110509_20131121_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2015/run/run_AMS-02_PRL2015_Proton_TKO_2.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2015/Input_Proton_TKO_20110509_20131121_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2015/run/run_AMS-02_PRL2015_Proton_TKO_3.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2015/Input_Proton_TKO_20110509_20131121_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2015/run/run_AMS-02_PRL2015_Proton_TKO_4.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2015/Input_Proton_TKO_20110509_20131121_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2015/run/run_AMS-02_PRL2015_Proton_TKO_5.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2015/Input_Proton_TKO_20110509_20131121_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2015/run/run_AMS-02_PRL2015_Proton_TKO_6.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2015/Input_Proton_TKO_20110509_20131121_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2015/run/run_AMS-02_PRL2015_Proton_TKO_7.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2015/Input_Proton_TKO_20110509_20131121_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2015/run/run_AMS-02_PRL2015_Proton_TKO_8.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2015/Input_Proton_TKO_20110509_20131121_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2015/run/run_AMS-02_PRL2015_Proton_TKO_9.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2015/Input_Deuteron_TKO_20110509_20131121_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2015/run/run_AMS-02_PRL2015_Proton_TKO_0.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2015/Input_Deuteron_TKO_20110509_20131121_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2015/run/run_AMS-02_PRL2015_Proton_TKO_1.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2015/Input_Deuteron_TKO_20110509_20131121_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2015/run/run_AMS-02_PRL2015_Proton_TKO_2.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2015/Input_Deuteron_TKO_20110509_20131121_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2015/run/run_AMS-02_PRL2015_Proton_TKO_3.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2015/Input_Deuteron_TKO_20110509_20131121_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2015/run/run_AMS-02_PRL2015_Proton_TKO_4.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2015/Input_Deuteron_TKO_20110509_20131121_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2015/run/run_AMS-02_PRL2015_Proton_TKO_5.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2015/Input_Deuteron_TKO_20110509_20131121_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2015/run/run_AMS-02_PRL2015_Proton_TKO_6.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2015/Input_Deuteron_TKO_20110509_20131121_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2015/run/run_AMS-02_PRL2015_Proton_TKO_7.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2015/Input_Deuteron_TKO_20110509_20131121_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2015/run/run_AMS-02_PRL2015_Proton_TKO_8.out 2>&1
CUDA_VISIBLE_DEVICES=4 $EXE -vv -i /home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2015/Input_Deuteron_TKO_20110509_20131121_r00100_lat00000.txt >/home/nfsdisk/DevGC/NewArchitecture/Cosmica_speed_test/Cosmica_V1-speedtest/runned_tests/AMS-02_PRL2015/run/run_AMS-02_PRL2015_Proton_TKO_9.out 2>&1
# CUDA_VISIBLE_DEVICES=4 only A30 board
# CUDA_VISIBLE_DEVICES=0,1,2,3 only x A40 board
echo Done....